### ISSUE TITLE
有没有发现很多复制粘贴也说没有

### ISSUE THREAD

**Issue by duoshoumiao** [Cathgao/Honkai_Starrail_bot#1]
emmmm

**Comment by Cathgao** [comment]
我看得懂中文但为什么看不懂你说什么

**Comment by duoshoumiao** [comment]
> 我看得懂中文但为什么看不懂你说什么

很明显阿。。.列表里面的名称复制出来搜材料，显示没有这个材料，去官方查又有。。。。

**Comment by Cathgao** [comment]
> > 我看得懂中文但为什么看不懂你说什么
> 
> 很明显阿。。.列表里面的名称复制出来搜材料，显示没有这个材料，去官方查又有。。。。

提供日志和截图

**Comment by Cathgao** [comment]
> > 我看得懂中文但为什么看不懂你说什么
> 
> 很明显阿。。.列表里面的名称复制出来搜材料，显示没有这个材料，去官方查又有。。。。

是不是跟原神bot冲突了被抢答

**Comment by duoshoumiao** [comment]
![(JYKZN{M_`5X~S1}W0LVPIH](https://user-images.githubusercontent.com/94856184/235350278-5bf18f54-9581-4b4e-95a8-c7b703e2be9d.jpg)
![(`LLJ KL1074}H3}FI 6X21](https://user-images.githubusercontent.com/94856184/235350290-9a6a457d-4b03-4b45-af93-0eb8a9aa9c0e.jpg)
感觉不是报错  而是名称标点符号问题

**Comment by duoshoumiao** [comment]
![(JYKZN{M_`5X~S1}W0LVPIH](https://user-images.githubusercontent.com/94856184/235350324-508f5b82-17f1-4f44-849c-fb09b8a82a59.jpg)

**Comment by Cathgao** [comment]
这个名称中间有标点，解析被分割了。我晚点修
